Update README.md
synicalsyntax/discord.js-heroku pull request #10
Opened 2018-11-01 00:07 UTC by akuinu

Added reminder about- web instead of worker dyno.
Common mistake by some people that's answer is hidden away in issues.

2018-11-01 00:20 UTC, synicalsyntax commented
Hi, thanks for the PR! @akuinu 

The notice reads fine at a glance, but I'm not sure if this is the right place to put this notice in the guide. If you read it as a whole, you'll notice that at this point we've only just created the Procfile and haven't actually created the Heroku application nor remotely built or launched the application yet. In order to flow with the guide more, you'd probably have to relocate it to a later section.

2018-11-01 09:10 UTC, akuinu commented
Relocated the information to Troubleshooting section near the end of the file.
Also added some basic troubleshooting hints

2018-11-02 00:30 UTC, synicalsyntax requested changes
Hi, thanks for updating! I commented with some areas that need improvement. 

Also, before I merge, can you please amend your original commit message to "Add Troubleshooting section to address web dyno issues." or something similar? Additionally, I'd like to request that you squash the changes in your second commit into your first commit so that there isn't 2 commits.

Thanks for your work so far!

2018-11-02 00:30 UTC, synicalsyntax commented on README.md
> +it is impossible to predict all potential problems.
Insert a new line afterwards.

2018-11-02 00:30 UTC, synicalsyntax commented on README.md
> +```sh
Can you be more explicit on what each of the commands does? Also, I believe you can combine scaling web and worker commands together; there's no need for 2 separate commands.

2018-11-02 00:30 UTC, synicalsyntax commented on README.md
> +`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`
Can you make this a full codeblock?

2018-11-02 00:30 UTC, synicalsyntax commented on README.md
> +Then you should check if you are running your app correct dyno - It should running it on worker and not on web,
See my previous comment about rephrasing; the dash isn't correct punctuation, "It should running" isn't proper grammar, "dyons" is misspelled, etc.

2018-11-02 00:30 UTC, synicalsyntax commented on README.md
> +If that is not your problem then you need to do some debugging on your own -
This phrase isn't very encouraging and sounds slightly condescending. Can you try rephrasing in a more positive manner?

2018-11-02 00:30 UTC, synicalsyntax commented on README.md
> +website and check under your app Resources tab or using command line `heroku ps`.
The guide focuses on the CLI instead of the web UI, so you can remove any references to the web app.

2018-11-02 00:30 UTC, synicalsyntax commented on README.md
> +Sometimes mistakes happen and like with most programming related problem - the solution is reading logs and documentation.
The grammar and punctuation here in this paragraph isn't correct, so it makes it awkward to read; for example, the dash would be better suited as a comma. Can you try rephrasing?

2018-11-15 19:34 UTC, synicalsyntax commented
Closing PR due to inactivity; if you want to work on it further, feel free to amend your commits and reopen. Thanks!

2018-11-15 19:35 UTC, closed without merging